language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.1
    - android-23

    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-23

before_install:
  - sudo pip install codecov

script:
  - ./gradlew build

after_failure:
  - if [ -e app/build/outputs/lint-results.xml ]; then cat app/build/outputs/lint-results.xml; else echo 'Not existent'; fe
after_success:
  - codecov
