language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.1
    - android-23

    - extra-google-m2repository
    - extra-android-m2repository

after_failure:
  if [ -e app/build/outputs/lint-results.xml ]; then cat app/build/outputs/lint-results.xml; else echo 'Not existent'; fi
