language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-23.0.3
    - android-23

    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-23

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew build jacocoTestDebugUnitTestReport

after_failure:
  - if [ -e app/build/outputs/lint-results.xml ]; then cat app/build/outputs/lint-results.xml; else echo 'Not existent'; fe
after_success:
  - bash <(curl -s https://codecov.io/bash)
